"""initial persistent translation and conversation aggregates

Revision ID: 46393c373925
Revises:
"""

from alembic import op
import sqlalchemy as sa

revision = "46393c373925"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "call_budgets",
        sa.Column("key", sa.String(length=180), nullable=False),
        sa.Column("used", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("tenant", sa.String(length=100), nullable=False),
        sa.Column("project", sa.String(length=100), nullable=False),
        sa.Column("subject_id", sa.String(length=80), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=60), nullable=False),
        sa.Column("body", sa.JSON(), nullable=False),
        sa.Column("raw_body", sa.Text(), nullable=False),
        sa.Column("created", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("subject_id", "sequence"),
    )
    op.create_index(op.f("ix_events_subject_id"), "events", ["subject_id"], unique=False)
    op.create_table(
        "idempotency",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("body_hash", sa.String(length=64), nullable=False),
        sa.Column("response", sa.JSON(), nullable=False),
        sa.Column("expires", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("tenant", sa.String(length=100), nullable=False),
        sa.Column("project", sa.String(length=100), nullable=False),
        sa.Column("owner", sa.String(length=200), nullable=False),
        sa.Column("translation_id", sa.String(length=80), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("stage", sa.String(length=24), nullable=False),
        sa.Column("source_id", sa.String(length=80), nullable=False),
        sa.Column("snapshot_id", sa.String(length=80), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created", sa.Float(), nullable=False),
        sa.Column("updated", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("translation_id", "revision"),
    )
    op.create_index(op.f("ix_jobs_project"), "jobs", ["project"], unique=False)
    op.create_index(op.f("ix_jobs_status"), "jobs", ["status"], unique=False)
    op.create_index(op.f("ix_jobs_tenant"), "jobs", ["tenant"], unique=False)
    op.create_index(op.f("ix_jobs_translation_id"), "jobs", ["translation_id"], unique=False)
    op.create_table(
        "messages",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("conversation_id", sa.String(length=80), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("client_message_id", sa.String(length=100), nullable=True),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("created", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("conversation_id", "client_message_id"),
        sa.UniqueConstraint("conversation_id", "sequence"),
    )
    op.create_index(op.f("ix_messages_conversation_id"), "messages", ["conversation_id"], unique=False)
    op.create_table(
        "model_calls",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("execution_key", sa.String(length=64), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("budget_key", sa.String(length=180), nullable=False),
        sa.Column("role", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("response", sa.JSON(), nullable=False),
        sa.Column("created", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("execution_key", "attempt"),
    )
    op.create_index(op.f("ix_model_calls_budget_key"), "model_calls", ["budget_key"], unique=False)
    op.create_index(op.f("ix_model_calls_execution_key"), "model_calls", ["execution_key"], unique=False)
    op.create_table(
        "model_slots",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("token", sa.String(length=80), nullable=False),
        sa.Column("expires", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "records",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("tenant", sa.String(length=100), nullable=False),
        sa.Column("project", sa.String(length=100), nullable=False),
        sa.Column("owner", sa.String(length=200), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created", sa.Float(), nullable=False),
        sa.Column("updated", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_records_kind"), "records", ["kind"], unique=False)
    op.create_index(op.f("ix_records_project"), "records", ["project"], unique=False)
    op.create_index("ix_records_scope_kind", "records", ["tenant", "project", "kind"], unique=False)
    op.create_index(op.f("ix_records_tenant"), "records", ["tenant"], unique=False)
    op.create_table(
        "segments",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("job_id", sa.String(length=80), nullable=False),
        sa.Column("source_id", sa.String(length=80), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("locator", sa.JSON(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "index"),
    )
    op.create_index(op.f("ix_segments_job_id"), "segments", ["job_id"], unique=False)
    op.create_table(
        "work",
        sa.Column("id", sa.String(length=140), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("target", sa.String(length=80), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("lease_token", sa.String(length=80), nullable=True),
        sa.Column("lease_until", sa.Float(), nullable=False),
        sa.Column("available_at", sa.Float(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.String(length=80), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_work_kind"), "work", ["kind"], unique=False)
    op.create_index(op.f("ix_work_status"), "work", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_work_status"), table_name="work")
    op.drop_index(op.f("ix_work_kind"), table_name="work")
    op.drop_table("work")
    op.drop_index(op.f("ix_segments_job_id"), table_name="segments")
    op.drop_table("segments")
    op.drop_index(op.f("ix_records_tenant"), table_name="records")
    op.drop_index("ix_records_scope_kind", table_name="records")
    op.drop_index(op.f("ix_records_project"), table_name="records")
    op.drop_index(op.f("ix_records_kind"), table_name="records")
    op.drop_table("records")
    op.drop_table("model_slots")
    op.drop_index(op.f("ix_model_calls_execution_key"), table_name="model_calls")
    op.drop_index(op.f("ix_model_calls_budget_key"), table_name="model_calls")
    op.drop_table("model_calls")
    op.drop_index(op.f("ix_messages_conversation_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_jobs_translation_id"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_tenant"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_status"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_project"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_table("idempotency")
    op.drop_index(op.f("ix_events_subject_id"), table_name="events")
    op.drop_table("events")
    op.drop_table("call_budgets")
    # ### end Alembic commands ###
